//! Servers (`kit push`, `kit remote`), the Linux shell environment, and `kit doctor`.
use crate::cli::Args;
use crate::core::*;
use crate::pkg::{s, split_spec};
use crate::util::*;
use serde_json::Value;
use sha2::{Digest, Sha256};
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

/// The scripts that run on servers, built into kit.
const REMOTE_FILES: &[(&str, &str)] = &[
    ("setup.sh", include_str!("../assets/remote/setup.sh")),
    ("hook.sh", include_str!("../assets/remote/hook.sh")),
    ("kit-env", include_str!("../assets/remote/kit-env")),
    ("kit-shell", include_str!("../assets/remote/kit-shell")),
];
const REMOTE_MAP: &[(&str, &str)] = &[(".config/", "config/"), (".fizsh/", "fizsh/")]; // what travels, and where it lands
const RC_FILES: &[&str] = &[".bashrc", ".bash_profile", ".bash_login", ".profile", ".zshrc", ".zprofile", ".fizsh/.zshrc"];
const KITTY: &str = "/Applications/kitty.app/Contents/Resources/kitty";

fn write_file(p: &Path, data: &[u8], mode: u32) {
    if let Some(parent) = p.parent() {
        let _ = fs::create_dir_all(parent);
    }
    let _ = fs::write(p, data);
    let _ = fs::set_permissions(p, fs::Permissions::from_mode(mode));
}

/// Everything setup.sh needs, for a server (mode=remote) or this Linux machine (mode=local).
pub fn build_payload(dest: &Path, mode: &str) -> String {
    if dest.exists() {
        let _ = fs::remove_dir_all(dest);
    }
    for sub in ["remote", "config", "fizsh", "share"] {
        let _ = fs::create_dir_all(dest.join(sub));
    }
    for (name, text) in REMOTE_FILES {
        write_file(&dest.join("remote").join(name), text.as_bytes(), 0o755);
    }
    write_file(&dest.join("mode"), format!("{mode}\n").as_bytes(), 0o644);
    let tracked = managed(None);
    if mode == "remote" {
        let ctxs = ["all", "linux", "remote"];
        for rel in &tracked {
            if ignored(rel, &ctxs) {
                continue;
            }
            for (prefix, target) in REMOTE_MAP {
                if let Some(rest) = rel.strip_prefix(prefix) {
                    let p = dest.join(target).join(rest);
                    if let Some(parent) = p.parent() {
                        let _ = fs::create_dir_all(parent);
                    }
                    match source_entry(rel, &ctxs) {
                        Ok(Some(Entry::Link(t))) => {
                            let _ = std::os::unix::fs::symlink(t, &p);
                        }
                        Ok(Some(Entry::File(b, m))) => write_file(&p, &b, if m & 0o111 != 0 { 0o755 } else { 0o644 }),
                        _ => {}
                    }
                    break;
                }
            }
        }
    }
    // rc files kit tracks on this machine: the login hook never goes into those
    let rc: String = tracked.iter().filter(|r| mode == "local" && RC_FILES.contains(&r.as_str())).map(|r| format!("{r}\n")).collect();
    write_file(&dest.join("managed-rc.list"), rc.as_bytes(), 0o644);
    // tools: a mise config generated from packages.json
    let mut lines = vec!["# generated by kit from packages.json — edit with `kit pkg ...`".to_string(), "[tools]".to_string()];
    let mut plist = String::new();
    for (n, p) in crate::pkg::all_packages() {
        let Some(linux) = s(&p, "linux") else { continue };
        if mode != "local" && !p.get("remote").and_then(Value::as_bool).unwrap_or(true) {
            continue;
        }
        let (base, ver) = split_spec(linux);
        let ver = ver.unwrap_or_else(|| "latest".into());
        lines.push(format!("{} = {}", Value::from(base.clone()), Value::from(ver.clone())));
        let fb = s(&p, "linux_fallback").map(|fb| {
            let (fbase, fver) = split_spec(fb);
            format!("{fbase}@{}", fver.unwrap_or_else(|| "latest".into()))
        });
        plist += &format!("{n} {} {base}@{ver} {}\n", s(&p, "bin").unwrap_or(&n), fb.unwrap_or_else(|| "-".into()));
    }
    write_file(&dest.join("mise.toml"), (lines.join("\n") + "\n").as_bytes(), 0o644);
    write_file(&dest.join("packages.list"), plist.as_bytes(), 0o644);
    let mut ext = String::new();
    for (rel, spec) in load_obj(&ctx().externals) {
        let rel = norm(&rel);
        if !rel.starts_with("..") && !rel.starts_with('/') {
            let url = spec.get("git").and_then(Value::as_str).unwrap_or("");
            ext += &format!("{rel} {url} {}\n", spec.get("ref").and_then(Value::as_str).unwrap_or(""));
        }
    }
    write_file(&dest.join("externals.list"), ext.as_bytes(), 0o644);
    let kitty = PathBuf::from(KITTY);
    if kitty.join("shell-integration").is_dir() {
        let _ = copy_dir(&kitty.join("shell-integration"), &dest.join("share/kitty/shell-integration"));
    }
    let ti = kitty.join("terminfo/78/xterm-kitty");
    if ti.is_file() {
        let _ = fs::create_dir_all(dest.join("share/terminfo/x"));
        let _ = fs::copy(&ti, dest.join("share/terminfo/x/xterm-kitty"));
    }
    let mut h = Sha256::new();
    let mut entries = Vec::new();
    walk_entries(dest, "", &mut entries, &mut |_, _| false);
    entries.sort();
    for rel in entries {
        let p = dest.join(&rel);
        if let Ok(t) = fs::read_link(&p) {
            h.update(format!("{rel}->{}", t.display()).as_bytes());
        } else {
            h.update(rel.as_bytes());
            h.update(b"\0");
            h.update(fs::read(&p).unwrap_or_default());
        }
    }
    let stamp = hex::encode(h.finalize())[..12].to_string();
    write_file(&dest.join(".stamp"), format!("{stamp}\n").as_bytes(), 0o644);
    stamp
}

fn ssh_opts() -> Vec<String> {
    ["-o", "ConnectTimeout=15", "-o", "ControlMaster=auto", "-o", "ControlPath=/tmp/kit-ssh-%C", "-o", "ControlPersist=60"]
        .iter()
        .map(|s| s.to_string())
        .collect()
}

fn ssh(host: &str, script: &str, capture: bool) -> Out {
    let mut cmd = vec!["ssh".to_string()];
    cmd.extend(ssh_opts());
    cmd.push(host.into());
    cmd.push(script.into());
    run(&cmd, capture)
}

fn not_sent_summary() -> String {
    let ctxs = ["all", "linux", "remote"];
    let rels = managed(None);
    let travels = |r: &str| REMOTE_MAP.iter().any(|(p, _)| r.starts_with(p));
    let outside: Vec<&String> = rels.iter().filter(|r| !travels(r)).collect();
    let kept = rels.iter().filter(|r| travels(r) && ignored(r, &ctxs)).count();
    let mut tops: Vec<String> = outside.iter().map(|r| r.split('/').take(2).collect::<Vec<_>>().join("/")).collect();
    tops.sort();
    tops.dedup();
    let mut msg = Vec::new();
    if !outside.is_empty() {
        let eg: Vec<String> = tops.iter().take(3).map(|t| format!("~/{t}")).collect();
        msg.push(format!("{} file(s) outside ~/.config and ~/.fizsh (e.g. {})", outside.len(), eg.join(", ")));
    }
    if kept > 0 {
        msg.push(format!("{kept} file(s) in .kitignore [remote]"));
    }
    msg.join(" · ")
}

pub fn cmd_push(a: &Args) {
    let cx = ctx();
    if !have("rsync") || !have("ssh") {
        die("kit push needs ssh and rsync");
    }
    guard_repo();
    let mut remotes = load_obj(&cx.remotes);
    if a.flag("remove") {
        let Some(host) = a.one("host") else { die("which server? kit push <host> --remove") };
        return remove_from(&host);
    }
    let hosts: Vec<String> = match a.one("host") {
        Some(h) => vec![h],
        None => remotes.keys().cloned().collect(),
    };
    if hosts.is_empty() {
        say("no servers yet — kit push <host> puts your environment on one");
        return;
    }
    let pending = file_changes(None, &load_synced()).into_iter().filter(|(c, _)| matches!(*c, "here" | "new" | "deleted" | "both")).count();
    if pending > 0 {
        warn(&format!("{pending} change(s) on this machine aren't in the repo, so servers get the repo's version (kit save first to send yours)"));
    }
    let payload = cx.state.join("payload");
    say("building");
    let stamp = build_payload(&payload, "remote");
    let summary = not_sent_summary();
    if !summary.is_empty() {
        note(&format!("not sent to servers: {summary}"));
    }
    for host in &hosts {
        if !remotes.contains_key(host) {
            out(&format!(
                "First push to {host}: your environment goes into ~/{REMOTE_KIT} there (about 1–2 GB with nvim's language servers),\n\
                 and a small block at the end of its ~/.bashrc makes interactive logins start your shell\n\
                 (scp, rsync and `ssh {host} <command>` are unaffected). Undo any time: kit push {host} --remove"
            ));
        }
        say(&format!("syncing to {host}"));
        if ssh(host, &format!("mkdir -p ~/{REMOTE_KIT}/payload"), false).code != 0 {
            fail(&format!("{host}: can't reach it over ssh"));
            continue;
        }
        let e = format!("ssh {}", ssh_opts().join(" "));
        let src = format!("{}/", payload.display());
        let dst = format!("{host}:{REMOTE_KIT}/payload/");
        if run(&["rsync", "-az", "--delete", "-e", &e, &src, &dst], false).code != 0 {
            fail(&format!("{host}: copying failed"));
            continue;
        }
        say(&format!("setting up {host}"));
        let rc = ssh(host, &format!("bash ~/{REMOTE_KIT}/payload/remote/setup.sh"), false).code;
        let record = |stamp: &str, at: &str| serde_json::json!({"stamp": stamp, "at": at});
        if rc == 0 {
            remotes.insert(host.clone(), record(&stamp, &chrono::Local::now().format("%Y-%m-%dT%H:%M").to_string()));
            save_json(&cx.remotes, &Value::Object(remotes.clone()));
        } else if rc == 255 {
            fail(&format!("{host}: lost the ssh connection during setup"));
        } else {
            remotes.entry(host.clone()).or_insert_with(|| record("", ""));
            save_json(&cx.remotes, &Value::Object(remotes.clone()));
            fail(&format!("{host}: setup reported problems (see above)"));
        }
    }
    if hosts.len() > 1 {
        say(if exit_code() == 0 { "done" } else { "done, with problems (see above)" });
    }
}

/// `kit push <host> --remove`: take kit off a server.
fn remove_from(host: &str) {
    let cx = ctx();
    let script = format!(
        "if [ -f ~/{REMOTE_KIT}/payload/remote/hook.sh ]; then bash ~/{REMOTE_KIT}/payload/remote/hook.sh remove; fi && rm -rf ~/{REMOTE_KIT} ~/.kit-off && echo \"kit removed from $(hostname)\""
    );
    if ssh(host, &script, false).code != 0 {
        fail(&format!("could not remove kit from {host}"));
        return;
    }
    let mut remotes = load_obj(&cx.remotes);
    remotes.remove(host);
    save_json(&cx.remotes, &Value::Object(remotes));
}

/// On a Linux machine you use directly: the same tested setup servers get (tools, zsh, nvim) in
/// ~/.local/kit, but using your real ~/.config and ~/.fizsh.
pub fn linux_environment() {
    let home = &ctx().home;
    say("setting up tools, zsh and nvim in ~/.local/kit");
    let payload = home.join(REMOTE_KIT).join("payload");
    build_payload(&payload, "local");
    let env = vec![("KIT_HOOK".to_string(), "0".to_string())];
    let setup = path_str(&payload.join("remote/setup.sh"));
    if run_full(&["bash", setup.as_str()], false, None, Some(&env), None).code != 0 {
        fail("environment setup reported problems (see above)");
    }
    crate::complete::install_completions(true); // kit's zsh now exists too
}
